package com.giseop.comebot.strategy.dto;

public enum CandidateReasonType {
    SELECTED,
    TREND_NOT_UP,
    PRICE_CHANGE_BELOW_THRESHOLD,
    TRADE_AMOUNT_CHANGE_BELOW_THRESHOLD,
    PRICE_CHANGE_OVERHEATED,
    HIGH_LOW_RANGE_OVERHEATED,
    NOT_ENOUGH_VALID_TRADE_AMOUNT,
    SCAN_FAILED,
    CONCENTRATION_RISK,
    STOP_LOSS_COOLDOWN,
    OTHER
}
