#!/usr/bin/env bash
set -euo pipefail

cd "$(dirname "$0")/.."

export STRATEGY_SELECTED="SESSION_VOLATILITY_BREAKOUT"
export TRADING_ALLOWED_MARKETS="ALL_USDT"
export TRADING_CANDIDATE_SCHEDULER_ENABLED="false"
export TRADING_CANDIDATE_SCHEDULER_MARKETS="ALL_USDT"
export TRADING_CANDIDATE_SCHEDULER_EXCHANGES="BINANCE"
export TRADING_CANDIDATE_SCHEDULER_MAX_BUYS_PER_RUN="1"
export STRATEGY_ENTRY_PREVENT_REENTRY_WITH_POSITION="true"
export TRADING_EXIT_SCHEDULER_ENABLED="false"
export TRADING_EXIT_SCHEDULER_FIXED_DELAY_MS="5000"
export TRADING_EXIT_SCHEDULER_EXCHANGES="BINANCE"
export SCHEDULER_CONTROL_RESTORE_ENABLED="false"

echo "Restarting Docker app/web with Session Volatility Binance PAPER profile."
docker compose up -d app web
