@echo off
setlocal

cd /d "%~dp0.."

set "STRATEGY_SELECTED=SESSION_VOLATILITY_BREAKOUT"
set "TRADING_ALLOWED_MARKETS=ALL_USDT"
set "TRADING_CANDIDATE_SCHEDULER_ENABLED=false"
set "TRADING_CANDIDATE_SCHEDULER_MARKETS=ALL_USDT"
set "TRADING_CANDIDATE_SCHEDULER_EXCHANGES=BINANCE"
set "TRADING_CANDIDATE_SCHEDULER_MAX_BUYS_PER_RUN=1"
set "STRATEGY_ENTRY_PREVENT_REENTRY_WITH_POSITION=true"
set "TRADING_EXIT_SCHEDULER_ENABLED=false"
set "TRADING_EXIT_SCHEDULER_FIXED_DELAY_MS=5000"
set "TRADING_EXIT_SCHEDULER_EXCHANGES=BINANCE"
set "SCHEDULER_CONTROL_RESTORE_ENABLED=false"

echo Restarting Docker app/web with Session Volatility Binance PAPER profile.
docker compose up -d app web
